create table fx_transfers (
 id bigint auto_increment primary key,
 household_id bigint not null,
 from_account_id bigint not null,
 to_account_id bigint not null,
 from_currency varchar(3) not null,
 to_currency varchar(3) not null,
 from_amount decimal(21,2) not null,
 to_amount decimal(21,2) not null,
 fee decimal(21,2) not null,
 occurred_on date not null,
 actor_id bigint not null,
 recorded_at timestamp(6) not null,
 revision bigint not null,
 reversed boolean not null,
 constraint fk_fx_from foreign key(from_account_id,household_id) references financial_accounts(id,household_id),
 constraint fk_fx_to foreign key(to_account_id,household_id) references financial_accounts(id,household_id),
 constraint fk_fx_actor foreign key(actor_id,household_id) references app_users(id,household_id),
 constraint ck_fx_amounts check(from_amount>0 and to_amount>0 and fee>=0 and revision>0),
 constraint ck_fx_distinct check(from_account_id<>to_account_id and from_currency<>to_currency),
 constraint ck_fx_transfer_currencies check(from_currency in ('CNY','HKD','USD') and to_currency in ('CNY','HKD','USD'))
);
create index ix_fx_transfer_household on fx_transfers(household_id,occurred_on,id);
create table fx_transfer_revisions (
 transfer_id bigint not null,
 revision bigint not null,
 operation varchar(10) not null,
 from_account_id bigint not null,
 to_account_id bigint not null,
 from_currency varchar(3) not null,
 to_currency varchar(3) not null,
 from_amount decimal(21,2) not null,
 to_amount decimal(21,2) not null,
 fee decimal(21,2) not null,
 occurred_on date not null,
 actor_id bigint not null,
 recorded_at timestamp(6) not null,
 primary key(transfer_id,revision),
 constraint fk_fx_revision_transfer foreign key(transfer_id) references fx_transfers(id),
 constraint ck_fx_operation check(operation in ('POST','REPLACE','REVERSE'))
);
