package com.familyfinance.loan;
import com.familyfinance.accounting.*;
import com.familyfinance.shared.ApiEnvelope; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping("/api/loans") public class LoanController { private final LoanService loans; private final LoanPrepaymentService prepayments; private final AccountingCommandExecutor executor; LoanController(LoanService loans,LoanPrepaymentService prepayments,AccountingCommandExecutor executor){this.loans=loans;this.prepayments=prepayments;this.executor=executor;}
 @GetMapping ResponseEntity<ApiEnvelope<LoanPage>> list(Authentication a,@RequestParam(defaultValue="ACTIVE") LoanStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){LoanPage p=loans.list(a,status,page,size);return ResponseEntity.ok().header("X-Page",String.valueOf(p.page())).header("X-Page-Size",String.valueOf(p.size())).header("X-Has-Next",String.valueOf(p.hasNext())).body(ApiEnvelope.data(p));}
 @GetMapping("/{id}") ApiEnvelope<LoanResponse> get(Authentication a,@PathVariable long id){return ApiEnvelope.data(loans.get(a,id));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) ApiEnvelope<LoanResponse> create(Authentication a,@RequestBody LoanCreateRequest r,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);return ApiEnvelope.data(executor.execute(()->loans.create(a,r,key)));}
 @PatchMapping("/{id}") ApiEnvelope<LoanResponse> update(Authentication a,@PathVariable long id,@RequestBody LoanPatchRequest r,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);return ApiEnvelope.data(executor.execute(()->loans.update(a,id,r,key)));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void archive(Authentication a,@PathVariable long id,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);executor.execute(()->{loans.archive(a,id,key);return null;});}
 @GetMapping("/{id}/schedule") ResponseEntity<ApiEnvelope<List<LoanInstallmentResponse>>> schedule(Authentication a,@PathVariable long id,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size){LoanSchedulePage p=loans.schedule(a,id,page,size);return ResponseEntity.ok().header("X-Page",String.valueOf(p.page())).header("X-Page-Size",String.valueOf(p.size())).header("X-Total-Elements",String.valueOf(p.totalElements())).header("X-Total-Pages",String.valueOf(p.totalPages())).header("X-Has-Next",String.valueOf(p.hasNext())).body(ApiEnvelope.data(p.items()));}
 @PostMapping("/{id}/prepay") ApiEnvelope<LoanPrepaymentResponse> prepay(Authentication a,@PathVariable long id,@RequestBody LoanPrepaymentRequest r){return ApiEnvelope.data(executor.execute(()->prepayments.prepay(a,id,r)));}
}
