import { useEffect, useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import Button from '@douyinfe/semi-ui/lib/es/button';
import type { Asset, AssetType, AssetValuation, HouseholdRole, Loan, Member, NetWorth, Page } from '../../api/contracts';
import { businessDate } from '../../shared/runtime';
import { PaginationControls, readAllPages, usePageRecovery } from '../../shared/pagination';
import { ConfirmDialog, DataPanel, Drawer, FormError, PageScaffold, QueryState, StatusTag, dateText, isManager, money, type RequestFn } from '../common';

export type AssetDraft = { id?: number; name: string; type: AssetType; ownerMemberId: string; acquiredOn: string; purchaseValue: string; currentValue: string; address: string; areaSqm: string; usageType: string; brandModel: string; plateHint: string; purchaseYear: string };
const blankAsset = (): AssetDraft => ({ name: '', type: 'PROPERTY', ownerMemberId: '', acquiredOn: '', purchaseValue: '', currentValue: '', address: '', areaSqm: '', usageType: '自住', brandModel: '', plateHint: '', purchaseYear: '' });

export function assetUpdatePayload(value: AssetDraft) {
  return {
    name: value.name,
    ownerMemberId: value.ownerMemberId ? Number(value.ownerMemberId) : null,
    property: value.type === 'PROPERTY' ? { address: value.address, areaSqm: value.areaSqm, usageType: value.usageType } : null,
    vehicle: value.type === 'VEHICLE' ? { brandModel: value.brandModel, plateHint: value.plateHint, purchaseYear: Number(value.purchaseYear) } : null
  };
}

export function AssetsPage({ request, role }: { request: RequestFn; role: HouseholdRole }) {
  const [type, setType] = useState('');
  const [draft, setDraft] = useState<AssetDraft | null>(null);
  const [valuationAsset, setValuationAsset] = useState<Asset | null>(null);
  const [valuation, setValuation] = useState({ valuedOn: businessDate(), value: '', note: '' });
  const [archiveId, setArchiveId] = useState<number | null>(null);
  const [assetPage, setAssetPage] = useState(0);
  const [valuationPage, setValuationPage] = useState(0);
  const assets = useQuery({ queryKey: ['assets', 'active-page', type, assetPage], queryFn: () => request<Page<Asset>>(`/api/assets?status=ACTIVE&page=${assetPage}&size=50${type ? `&type=${type}` : ''}`, { responseType: 'page' }) });
  const members = useQuery({ queryKey: ['members'], queryFn: () => request<Member[]>('/api/members') });
  const netWorth = useQuery({ queryKey: ['net-worth'], queryFn: () => request<NetWorth>('/api/net-worth') });
  const loans = useQuery({ queryKey: ['loans', 'active-all-options'], queryFn: () => readAllPages(page => request<Page<Loan>>(`/api/loans?status=ACTIVE&page=${page}&size=50`, { responseType: 'page' })) });
  const valuations = useQuery({ queryKey: ['asset-valuations', valuationAsset?.id, valuationPage], queryFn: () => request<Page<AssetValuation>>(`/api/assets/${valuationAsset!.id}/valuations?page=${valuationPage}&size=20`, { responseType: 'page' }), enabled: valuationAsset !== null });
  useEffect(() => { setAssetPage(0); }, [type]);
  usePageRecovery(assetPage, assets.data, setAssetPage);
  usePageRecovery(valuationPage, valuations.data, setValuationPage);
  const save = useMutation({ mutationFn: (value: AssetDraft) => request<Asset>(value.id ? `/api/assets/${value.id}` : '/api/assets', { method: value.id ? 'PATCH' : 'POST', body: value.id ? assetUpdatePayload(value) : { name: value.name, type: value.type, ownerMemberId: value.ownerMemberId ? Number(value.ownerMemberId) : null, acquiredOn: value.acquiredOn || null, purchaseValue: value.purchaseValue || null, currentValue: value.currentValue, property: value.type === 'PROPERTY' ? { address: value.address, areaSqm: value.areaSqm, usageType: value.usageType } : null, vehicle: value.type === 'VEHICLE' ? { brandModel: value.brandModel, plateHint: value.plateHint, purchaseYear: Number(value.purchaseYear) } : null } }), onSuccess: () => { setDraft(null); } });
  const addValuation = useMutation({ mutationFn: () => request<AssetValuation>(`/api/assets/${valuationAsset!.id}/valuations`, { method: 'POST', body: valuation }), onSuccess: () => { setValuation({ valuedOn: businessDate(), value: '', note: '' }); } });
  const archive = useMutation({ mutationFn: (id: number) => request<void>(`/api/assets/${id}`, { method: 'DELETE' }), onSuccess: () => { setArchiveId(null); } });
  const manager = isManager(role);
  const edit = (item: Asset): AssetDraft => ({ id: item.id, name: item.name, type: item.type, ownerMemberId: String(item.ownerMemberId ?? ''), acquiredOn: item.acquiredOn ?? '', purchaseValue: item.purchaseValue ?? '', currentValue: item.currentValue, address: item.property?.address ?? '', areaSqm: String(item.property?.areaSqm ?? ''), usageType: item.property?.usageType ?? '自住', brandModel: item.vehicle?.brandModel ?? '', plateHint: item.vehicle?.plateHint ?? '', purchaseYear: String(item.vehicle?.purchaseYear ?? '') });
  const typeLabel = (value: AssetType) => value === 'PROPERTY' ? '房产' : value === 'VEHICLE' ? '车辆' : '其他';
  const loanFor = (id: number) => loans.data?.find(item => item.linkedAssetId === id);
  return <PageScaffold title="资产账户" primaryAction={manager ? { label: '新建资产', onClick: () => setDraft(blankAsset()) } : undefined} readonly={!manager}>
    <div className="summary-strip"><div><span>家庭总资产</span><strong>{netWorth.isLoading ? '读取中' : money(netWorth.data?.asset)}</strong><small>当前家庭资产汇总</small></div><div><span>非现金资产</span><strong>{assets.data?.totalElements ?? '—'} 项</strong><small>当前筛选内活跃资产</small></div><div><span>关联贷款</span><strong>{loans.data?.filter(item => item.linkedAssetId).length ?? '—'} 笔</strong><small>已关联的活跃贷款</small></div></div>
    <div className="toolbar"><div className="pill-filter" role="group" aria-label="资产类型"><button className={!type ? 'active' : ''} onClick={() => setType('')}>全部</button>{(['PROPERTY','VEHICLE','OTHER'] as AssetType[]).map(value => <button className={type === value ? 'active' : ''} key={value} onClick={() => setType(value)}>{typeLabel(value)}</button>)}</div></div>
    <QueryState loading={assets.isLoading} error={assets.error} empty={!assets.data?.items.length && assetPage === 0} emptyTitle="还没有资产" emptyDetail={manager ? '添加房产、车辆或其他非现金资产。' : '家庭管理员还没有录入资产。'}>
      <><div className="responsive-data"><table><thead><tr><th>资产</th><th>类型</th><th>购入价值</th><th>当前价值</th><th>关联贷款</th><th>持有信息</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{assets.data?.items.map(item => { const linkedLoan = loanFor(item.id); return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.property?.address ?? item.vehicle?.brandModel ?? dateText(item.acquiredOn)}</small></td><td><StatusTag tone="blue">{typeLabel(item.type)}</StatusTag></td><td>{money(item.purchaseValue)}</td><td className="money"><strong>{money(item.currentValue)}</strong></td><td>{linkedLoan ? <><strong>{money(linkedLoan.currentPrincipal)}</strong><small>{linkedLoan.name}</small></> : <span className="muted">未关联</span>}</td><td>{item.property ? `${item.property.areaSqm}㎡ · ${item.property.usageType}` : item.vehicle ? `${item.vehicle.purchaseYear} · ${item.vehicle.plateHint || '车牌未填'}` : '—'}</td><td>{manager && <><button className="text-action" onClick={() => { setValuationPage(0); setValuationAsset(item); }}>估值</button><button className="text-action" onClick={() => setDraft(edit(item))}>编辑</button><button className="text-action danger" onClick={() => setArchiveId(item.id)}>归档</button></>}</td></tr>; })}</tbody></table><div className="mobile-card-list">{assets.data?.items.map(item => <article className="record-card asset-card" key={item.id}><header><div><StatusTag tone="blue">{typeLabel(item.type)}</StatusTag><strong>{item.name}</strong></div><b>{money(item.currentValue)}</b></header><p>{item.property?.address ?? item.vehicle?.brandModel ?? dateText(item.acquiredOn)}</p>{manager && <footer><button onClick={() => { setValuationPage(0); setValuationAsset(item); }}>更新估值</button><span><button onClick={() => setDraft(edit(item))}>编辑</button><button onClick={() => setArchiveId(item.id)}>归档</button></span></footer>}</article>)}</div></div><PaginationControls page={assetPage} totalPages={assets.data?.totalPages ?? 0} hasNext={assets.data?.hasNext ?? false} onPageChange={setAssetPage} label="资产" /></>
    </QueryState>
    <Drawer draft={draft} sessionKey={draft?.id} busy={save.isPending} onSessionStart={save.reset} open={draft !== null} title={draft?.id ? '编辑资产' : '新建资产'} description="现金和银行卡请在账户中管理，避免重复计入净资产。" onClose={() => setDraft(null)}>{draft && <form className="feature-form" onSubmit={(e: FormEvent) => { e.preventDefault(); save.mutate(draft); }}><FormError error={save.error} /><label>资产名称<input name="name" required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>资产类型<select name="type" disabled={Boolean(draft.id)} value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value as AssetType })}><option value="PROPERTY">房产</option><option value="VEHICLE">车辆</option><option value="OTHER">其他</option></select></label><label>归属成员<select name="ownerMemberId" value={draft.ownerMemberId} onChange={e => setDraft({ ...draft, ownerMemberId: e.target.value })}><option value="">家庭共有</option>{members.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>购入日期<input name="acquiredOn" type="date" disabled={Boolean(draft.id)} value={draft.acquiredOn} onChange={e => setDraft({ ...draft, acquiredOn: e.target.value })} /></label><label>购入价值<input name="purchaseValue" inputMode="decimal" disabled={Boolean(draft.id)} value={draft.purchaseValue} onChange={e => setDraft({ ...draft, purchaseValue: e.target.value })} /></label><label>当前价值<input name="currentValue" required inputMode="decimal" disabled={Boolean(draft.id)} value={draft.currentValue} onChange={e => setDraft({ ...draft, currentValue: e.target.value })} /></label>{draft.id && <p className="field-help">类型与购入信息保留历史；需要调整当前价值，请使用“估值”。</p>}{draft.type === 'PROPERTY' && <fieldset data-field="property" tabIndex={-1}><legend>房产信息</legend><label>地址<input name="address" required value={draft.address} onChange={e => setDraft({ ...draft, address: e.target.value })} /></label><label>面积（㎡）<input name="areaSqm" required inputMode="decimal" value={draft.areaSqm} onChange={e => setDraft({ ...draft, areaSqm: e.target.value })} /></label><label>用途<input name="usageType" required value={draft.usageType} onChange={e => setDraft({ ...draft, usageType: e.target.value })} /></label></fieldset>}{draft.type === 'VEHICLE' && <fieldset data-field="vehicle" tabIndex={-1}><legend>车辆信息</legend><label>品牌型号<input name="brandModel" required value={draft.brandModel} onChange={e => setDraft({ ...draft, brandModel: e.target.value })} /></label><label>车牌提示<input name="plateHint" value={draft.plateHint} onChange={e => setDraft({ ...draft, plateHint: e.target.value })} /></label><label>购车年份<input name="purchaseYear" type="number" required value={draft.purchaseYear} onChange={e => setDraft({ ...draft, purchaseYear: e.target.value })} /></label></fieldset>}<Button htmlType="submit" theme="solid" type="primary" loading={save.isPending}>保存资产</Button></form>}</Drawer>
    <Drawer draft={valuation} sessionKey={valuationAsset?.id} savedKey={addValuation.data} busy={addValuation.isPending} onSessionStart={addValuation.reset} open={valuationAsset !== null} title={`更新估值 · ${valuationAsset?.name ?? ''}`} description="同日手工估值会更正当天记录，历史日期仍然保留。" onClose={() => { setValuationAsset(null); setValuationPage(0); setValuation({ valuedOn: businessDate(), value: '', note: '' }); }}><form className="feature-form" onSubmit={e => { e.preventDefault(); addValuation.mutate(); }}><FormError error={addValuation.error} /><label>估值日期<input name="valuedOn" type="date" value={valuation.valuedOn} onChange={e => setValuation({ ...valuation, valuedOn: e.target.value })} /></label><label>当前价值<input name="value" required inputMode="decimal" value={valuation.value} onChange={e => setValuation({ ...valuation, value: e.target.value })} /></label><label>依据说明<textarea name="note" value={valuation.note} onChange={e => setValuation({ ...valuation, note: e.target.value })} /></label><Button htmlType="submit" theme="solid" type="primary" loading={addValuation.isPending}>保存估值</Button></form><DataPanel title="估值历史"><QueryState loading={valuations.isLoading} error={valuations.error} empty={!valuations.data?.items.length && valuationPage === 0}><><ol className="timeline-list">{valuations.data?.items.map(item => <li key={item.id}><i /><div><strong>{money(item.value)}</strong><p>{dateText(item.valuedOn)} · {item.source === 'MANUAL' ? '手工估值' : '购入价值'}{item.note ? ` · ${item.note}` : ''}</p></div></li>)}</ol><PaginationControls page={valuationPage} totalPages={valuations.data?.totalPages ?? 0} hasNext={valuations.data?.hasNext ?? false} onPageChange={setValuationPage} label="估值历史" /></></QueryState></DataPanel></Drawer>
    <ConfirmDialog open={archiveId !== null} loading={archive.isPending} title="归档这项资产？" detail={<><p>归档后不再计入当前净资产，估值历史仍会保留。</p><FormError error={archive.error} /></>} danger confirmLabel="归档资产" onClose={() => { setArchiveId(null); archive.reset(); }} onConfirm={() => archiveId !== null && archive.mutate(archiveId)} />
  </PageScaffold>;
}
