create table fx_sync_state (id bigint primary key);
insert into fx_sync_state(id) values (1);
create table fx_rate_batches (
    id bigint generated by default as identity primary key,
    source varchar(20) not null,
    effective_on date not null,
    fetched_at timestamp(6) not null,
    revision integer not null,
    payload_hash varchar(64) not null,
    constraint uk_fx_batch_revision unique(source,effective_on,revision),
    constraint ck_fx_revision check(revision>0)
);
create table fx_rates (
    batch_id bigint not null,
    currency varchar(3) not null,
    cny_per_unit decimal(30,12) not null,
    primary key(batch_id,currency),
    constraint fk_fx_rate_batch foreign key(batch_id) references fx_rate_batches(id),
    constraint ck_fx_currency check(currency in ('HKD','USD')),
    constraint ck_fx_positive check(cny_per_unit>0)
);
