create table net_worth_snapshot_revisions (
 id bigint generated by default as identity primary key,
 snapshot_id bigint not null,
 asset_cents bigint not null,
 liability_cents bigint not null,
 net_worth_cents bigint not null,
 recorded_at timestamp(6) not null,
 constraint fk_net_worth_revision foreign key(snapshot_id) references net_worth_snapshots(id)
);
create index ix_net_worth_revision on net_worth_snapshot_revisions(snapshot_id,id);
